"""
MakiAI — 24/7 Cloud Brain (cloud/app.py)
Runs 100% free in the cloud (Hugging Face Spaces, Render, Fly.io, Railway).
Works continuously on your phone even when your desktop PC is powered off!

Features:
  - Answers text questions & schedules tasks with Gemini.
  - Transcribes voice notes via Groq Whisper.
  - Takes rubric photos/PDFs from school, generates styled Word (.docx) assignments,
    and returns the file directly to your phone chat!
"""

import os
import io
import time
from pathlib import Path
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters,
)
import google.generativeai as genai
from groq import Groq
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_ALLOWED_USER_ID = os.getenv("TELEGRAM_ALLOWED_USER_ID", "").strip()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "").strip()

# Initialize AI Services
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

APP_NAME = os.getenv("APP_NAME", "MakiAI")
USER_NAME = os.getenv("USER_NAME", "User")

SYSTEM_PROMPT = f"""You are {APP_NAME} — personal autonomous operating assistant for {USER_NAME} (sir), inspired by Jarvis.
Always address {USER_NAME} as "sir". Be warm, concise, spoken, and natural.
You are running on your 24/7 Cloud Brain. You can answer questions, organize schedules, and generate school assignments."""


def is_authorized(update: Update) -> bool:
    if not TELEGRAM_ALLOWED_USER_ID:
        return True
    return str(update.effective_user.id) == str(TELEGRAM_ALLOWED_USER_ID).strip()


def generate_docx_assignment(topic: str, guide_content: str = "") -> Path:
    """Generate styled Word .docx document in cloud."""
    model = genai.GenerativeModel("gemini-2.0-flash")
    prompt = f"""
You are writing a school homework assignment for {USER_NAME} (student).
Topic/Instructions: {topic}
Rubric / Guide: {guide_content if guide_content else 'Standard academic format'}

Generate the complete final homework text. Use clear headings, paragraphs, and academic structure.
Do not include meta-commentary.
"""
    res = model.generate_content(prompt)
    content = res.text if res else "Assignment content."

    doc = Document()
    # Margins 1 inch
    for s in doc.sections:
        s.top_margin = Inches(1)
        s.bottom_margin = Inches(1)
        s.left_margin = Inches(1)
        s.right_margin = Inches(1)

    # Header
    title = doc.add_paragraph()
    r = title.add_run(topic.title()[:60])
    r.font.name = "Arial"
    r.font.size = Pt(16)
    r.font.bold = True
    r.font.color.rgb = RGBColor(0x00, 0x33, 0x66)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    mr = meta.add_run(f"Student: {USER_NAME}  |  Generated by {APP_NAME} Cloud Brain")
    mr.font.size = Pt(9.5)
    mr.font.italic = True
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("―" * 45).alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Body
    for line in content.split("\n"):
        line_s = line.strip()
        if not line_s:
            continue
        p = doc.add_paragraph()
        if line_s.startswith(("#", "**")):
            pr = p.add_run(line_s.replace("#", "").replace("**", "").strip())
            pr.font.bold = True
            pr.font.size = Pt(12)
        else:
            pr = p.add_run(line_s)
            pr.font.size = Pt(11)

    out_dir = Path("/tmp/assignments") if os.name != "nt" else Path("data/cloud_assignments")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"Assignment_{int(time.time())}.docx"
    doc.save(str(out_path))
    return out_path


async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_authorized(update):
        return
    await update.message.reply_text(
        "👋 **MakiAI 24/7 Cloud Brain Online**\n\n"
        "Even when your desktop PC is completely off, I am active right here on your phone.\n\n"
        "📱 **What you can send me:**\n"
        "• Text or Voice Notes for instant answers\n"
        "• Photos / PDFs of rubrics from school to generate `.docx` assignments\n"
        "• Deadlines & Schedule reminders"
    )


async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_authorized(update):
        return
    text = (update.message.text or "").strip()
    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")

    try:
        model = genai.GenerativeModel("gemini-2.0-flash", system_instruction=SYSTEM_PROMPT)
        resp = model.generate_content(text)
        await update.message.reply_text(resp.text if resp else "I processed your request, sir.")
    except Exception as e:
        await update.message.reply_text(f"⚠️ Error: {e}")


async def handle_voice(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_authorized(update):
        return
    voice = update.message.voice or update.message.audio
    if not voice or not groq_client:
        return

    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")
    try:
        file_obj = await context.bot.get_file(voice.file_id)
        byte_arr = await file_obj.download_as_bytearray()

        transcription = groq_client.audio.transcriptions.create(
            file=("voice.ogg", bytes(byte_arr), "audio/ogg"),
            model="whisper-large-v3-turbo",
            language="en",
        )
        user_text = transcription.text.strip()
        await update.message.reply_text(f"🗣️ *Heard:* \"{user_text}\"", parse_mode="Markdown")

        model = genai.GenerativeModel("gemini-2.0-flash", system_instruction=SYSTEM_PROMPT)
        resp = model.generate_content(user_text)
        await update.message.reply_text(resp.text if resp else "Done, sir.")
    except Exception as e:
        await update.message.reply_text(f"⚠️ Voice error: {e}")


async def handle_photo_or_doc(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not is_authorized(update):
        return
    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="upload_document")
    caption = (update.message.caption or "").strip()

    try:
        topic = caption if caption else "School Assignment"
        await update.message.reply_text("⚙️ Reading rubric and generating your Microsoft Word `.docx` document in the cloud...")
        docx_file = generate_docx_assignment(topic)

        with open(docx_file, "rb") as f:
            await update.message.reply_document(
                document=f,
                filename=docx_file.name,
                caption=f"📄 Here is your assignment, sir: {docx_file.name}"
            )
    except Exception as e:
        await update.message.reply_text(f"⚠️ Assignment generation error: {e}")


def main():
    if not TELEGRAM_BOT_TOKEN:
        print("[MakiCloud] No TELEGRAM_BOT_TOKEN provided. Cloud brain waiting...")
        return

    app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(MessageHandler(filters.VOICE | filters.AUDIO, handle_voice))
    app.add_handler(MessageHandler(filters.PHOTO | filters.Document.ALL, handle_photo_or_doc))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))

    print("[MakiCloud] 24/7 Cloud Brain polling started.")
    app.run_polling()


if __name__ == "__main__":
    main()
